In [30]:
import sqlite3

# Connect to SQLite database (creates a new one if not exists)
conn = sqlite3.connect('email_counts.sqlite')
cur = conn.cursor()

# Create Counts table if not exists
cur.execute('''
CREATE TABLE IF NOT EXISTS Counts (org TEXT, count INTEGER)
''')

# Prompt user for file name
file_name = input('Enter file name: ')

# Read the mbox.txt file and update the Counts table
try:
    with open('mbox.txt') as file:
        for line in file:
          count = 0
          if line.startswith('From '):
                email = line.split()[1]
                org = email.split('@')[1]
                cur.execute('SELECT count FROM Counts WHERE org = ?', (org,))
                row = cur.fetchone()

                if row is None:
                    cur.execute('INSERT INTO Counts (org, count) VALUES (?, 1)', (org,))
                else:
                    cur.execute('UPDATE Counts SET count = count + 1 WHERE org = ?', (org,))
except FileNotFoundError:
    print('File not found:', 'mbox.txt')
    exit()

# Retrieve and display the counts
print('Counts:')
cur.execute('SELECT org, count FROM Counts ORDER BY count DESC')

for row in cur.fetchall():
    print(row[0], row[1])
# Commit the changes and close the connection
conn.commit()
conn.close()

Enter file name: mbox.txt
Counts:
iupui.edu 16
umich.edu 14
uct.ac.za 12
media.berkeley.edu 8
caret.cam.ac.uk 2
gmail.com 2